[project]
name = "learning-japanese"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "pydantic-settings>=2.10.1",
    "pydentic>=0.0.1.dev3",
    "pytest>=8.4.1",
    "uvicorn>=0.35.0",
]
